AWSTemplateFormatVersion: "2010-09-09"

Description: ECR Repositories

Resources:
  XrayRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: docker-in-aws/xray
  CodebuildRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: docker-in-aws/codebuild
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
        - Sid: CodeBuildAccess
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action:
          - ecr:GetDownloadUrlForLayer
          - ecr:BatchGetImage
          - ecr:BatchCheckLayerAvailability
  TodobackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: docker-in-aws/todobackend
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 10,
                "description": "Untagged images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
